if(EXISTS "/Users/fuch/Document/Smart_Telega/smart-cart/build_qt/integration_tests[1]_tests.cmake")
  include("/Users/fuch/Document/Smart_Telega/smart-cart/build_qt/integration_tests[1]_tests.cmake")
else()
  add_test(integration_tests_NOT_BUILT integration_tests_NOT_BUILT)
endif()
